# Generated by Django 4.0.5 on 2022-07-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_course_semester_subject_studentprofile_staffprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='ClassName',
        ),
        migrations.RenameModel(
            old_name='Semester',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='classname',
            old_name='courseName',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='course',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='semester',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='semester',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.classname'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
