# Generated by Django 4.0.5 on 2022-07-17 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_course_classname_rename_semester_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('className', 'section')},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contactNo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fatherName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
