# Generated by Django 4.0.5 on 2022-07-26 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['className']},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contactNo',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,12}$')]),
        ),
    ]
