# Generated by Django 4.0.5 on 2022-07-26 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_classname_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='contactNo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')]),
        ),
    ]
